// Generated by gencpp from file robotarm/Robot_StopResponse.msg
// DO NOT EDIT!


#ifndef ROBOTARM_MESSAGE_ROBOT_STOPRESPONSE_H
#define ROBOTARM_MESSAGE_ROBOT_STOPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotarm
{
template <class ContainerAllocator>
struct Robot_StopResponse_
{
  typedef Robot_StopResponse_<ContainerAllocator> Type;

  Robot_StopResponse_()
    {
    }
  Robot_StopResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::robotarm::Robot_StopResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotarm::Robot_StopResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Robot_StopResponse_

typedef ::robotarm::Robot_StopResponse_<std::allocator<void> > Robot_StopResponse;

typedef boost::shared_ptr< ::robotarm::Robot_StopResponse > Robot_StopResponsePtr;
typedef boost::shared_ptr< ::robotarm::Robot_StopResponse const> Robot_StopResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotarm::Robot_StopResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotarm::Robot_StopResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotarm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotarm::Robot_StopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotarm::Robot_StopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarm::Robot_StopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarm::Robot_StopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarm::Robot_StopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarm::Robot_StopResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotarm::Robot_StopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robotarm::Robot_StopResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robotarm::Robot_StopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotarm/Robot_StopResponse";
  }

  static const char* value(const ::robotarm::Robot_StopResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotarm::Robot_StopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::robotarm::Robot_StopResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotarm::Robot_StopResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Robot_StopResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotarm::Robot_StopResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robotarm::Robot_StopResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTARM_MESSAGE_ROBOT_STOPRESPONSE_H
