// Generated by gencpp from file robotarm/Robot_Stop.msg
// DO NOT EDIT!


#ifndef ROBOTARM_MESSAGE_ROBOT_STOP_H
#define ROBOTARM_MESSAGE_ROBOT_STOP_H

#include <ros/service_traits.h>


#include <robotarm/Robot_StopRequest.h>
#include <robotarm/Robot_StopResponse.h>


namespace robotarm
{

struct Robot_Stop
{

typedef Robot_StopRequest Request;
typedef Robot_StopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Robot_Stop
} // namespace robotarm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotarm::Robot_Stop > {
  static const char* value()
  {
    return "019706110004b728d56d8baaa8e32797";
  }

  static const char* value(const ::robotarm::Robot_Stop&) { return value(); }
};

template<>
struct DataType< ::robotarm::Robot_Stop > {
  static const char* value()
  {
    return "robotarm/Robot_Stop";
  }

  static const char* value(const ::robotarm::Robot_Stop&) { return value(); }
};


// service_traits::MD5Sum< ::robotarm::Robot_StopRequest> should match 
// service_traits::MD5Sum< ::robotarm::Robot_Stop > 
template<>
struct MD5Sum< ::robotarm::Robot_StopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotarm::Robot_Stop >::value();
  }
  static const char* value(const ::robotarm::Robot_StopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotarm::Robot_StopRequest> should match 
// service_traits::DataType< ::robotarm::Robot_Stop > 
template<>
struct DataType< ::robotarm::Robot_StopRequest>
{
  static const char* value()
  {
    return DataType< ::robotarm::Robot_Stop >::value();
  }
  static const char* value(const ::robotarm::Robot_StopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotarm::Robot_StopResponse> should match 
// service_traits::MD5Sum< ::robotarm::Robot_Stop > 
template<>
struct MD5Sum< ::robotarm::Robot_StopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotarm::Robot_Stop >::value();
  }
  static const char* value(const ::robotarm::Robot_StopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotarm::Robot_StopResponse> should match 
// service_traits::DataType< ::robotarm::Robot_Stop > 
template<>
struct DataType< ::robotarm::Robot_StopResponse>
{
  static const char* value()
  {
    return DataType< ::robotarm::Robot_Stop >::value();
  }
  static const char* value(const ::robotarm::Robot_StopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTARM_MESSAGE_ROBOT_STOP_H
