// Generated by gencpp from file robotarm/Robot_Status.msg
// DO NOT EDIT!


#ifndef ROBOTARM_MESSAGE_ROBOT_STATUS_H
#define ROBOTARM_MESSAGE_ROBOT_STATUS_H

#include <ros/service_traits.h>


#include <robotarm/Robot_StatusRequest.h>
#include <robotarm/Robot_StatusResponse.h>


namespace robotarm
{

struct Robot_Status
{

typedef Robot_StatusRequest Request;
typedef Robot_StatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Robot_Status
} // namespace robotarm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotarm::Robot_Status > {
  static const char* value()
  {
    return "e2e2601b88f78908f1405936821fcd9f";
  }

  static const char* value(const ::robotarm::Robot_Status&) { return value(); }
};

template<>
struct DataType< ::robotarm::Robot_Status > {
  static const char* value()
  {
    return "robotarm/Robot_Status";
  }

  static const char* value(const ::robotarm::Robot_Status&) { return value(); }
};


// service_traits::MD5Sum< ::robotarm::Robot_StatusRequest> should match 
// service_traits::MD5Sum< ::robotarm::Robot_Status > 
template<>
struct MD5Sum< ::robotarm::Robot_StatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotarm::Robot_Status >::value();
  }
  static const char* value(const ::robotarm::Robot_StatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotarm::Robot_StatusRequest> should match 
// service_traits::DataType< ::robotarm::Robot_Status > 
template<>
struct DataType< ::robotarm::Robot_StatusRequest>
{
  static const char* value()
  {
    return DataType< ::robotarm::Robot_Status >::value();
  }
  static const char* value(const ::robotarm::Robot_StatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotarm::Robot_StatusResponse> should match 
// service_traits::MD5Sum< ::robotarm::Robot_Status > 
template<>
struct MD5Sum< ::robotarm::Robot_StatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotarm::Robot_Status >::value();
  }
  static const char* value(const ::robotarm::Robot_StatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotarm::Robot_StatusResponse> should match 
// service_traits::DataType< ::robotarm::Robot_Status > 
template<>
struct DataType< ::robotarm::Robot_StatusResponse>
{
  static const char* value()
  {
    return DataType< ::robotarm::Robot_Status >::value();
  }
  static const char* value(const ::robotarm::Robot_StatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTARM_MESSAGE_ROBOT_STATUS_H
