// Generated by gencpp from file robotarm/Robot_Set_Park.msg
// DO NOT EDIT!


#ifndef ROBOTARM_MESSAGE_ROBOT_SET_PARK_H
#define ROBOTARM_MESSAGE_ROBOT_SET_PARK_H

#include <ros/service_traits.h>


#include <robotarm/Robot_Set_ParkRequest.h>
#include <robotarm/Robot_Set_ParkResponse.h>


namespace robotarm
{

struct Robot_Set_Park
{

typedef Robot_Set_ParkRequest Request;
typedef Robot_Set_ParkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Robot_Set_Park
} // namespace robotarm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotarm::Robot_Set_Park > {
  static const char* value()
  {
    return "15c5ba1c738eafebff9be7bf85aaac80";
  }

  static const char* value(const ::robotarm::Robot_Set_Park&) { return value(); }
};

template<>
struct DataType< ::robotarm::Robot_Set_Park > {
  static const char* value()
  {
    return "robotarm/Robot_Set_Park";
  }

  static const char* value(const ::robotarm::Robot_Set_Park&) { return value(); }
};


// service_traits::MD5Sum< ::robotarm::Robot_Set_ParkRequest> should match 
// service_traits::MD5Sum< ::robotarm::Robot_Set_Park > 
template<>
struct MD5Sum< ::robotarm::Robot_Set_ParkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotarm::Robot_Set_Park >::value();
  }
  static const char* value(const ::robotarm::Robot_Set_ParkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotarm::Robot_Set_ParkRequest> should match 
// service_traits::DataType< ::robotarm::Robot_Set_Park > 
template<>
struct DataType< ::robotarm::Robot_Set_ParkRequest>
{
  static const char* value()
  {
    return DataType< ::robotarm::Robot_Set_Park >::value();
  }
  static const char* value(const ::robotarm::Robot_Set_ParkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotarm::Robot_Set_ParkResponse> should match 
// service_traits::MD5Sum< ::robotarm::Robot_Set_Park > 
template<>
struct MD5Sum< ::robotarm::Robot_Set_ParkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotarm::Robot_Set_Park >::value();
  }
  static const char* value(const ::robotarm::Robot_Set_ParkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotarm::Robot_Set_ParkResponse> should match 
// service_traits::DataType< ::robotarm::Robot_Set_Park > 
template<>
struct DataType< ::robotarm::Robot_Set_ParkResponse>
{
  static const char* value()
  {
    return DataType< ::robotarm::Robot_Set_Park >::value();
  }
  static const char* value(const ::robotarm::Robot_Set_ParkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTARM_MESSAGE_ROBOT_SET_PARK_H
