// Generated by gencpp from file robotarm/Robot_Set_Ready.msg
// DO NOT EDIT!


#ifndef ROBOTARM_MESSAGE_ROBOT_SET_READY_H
#define ROBOTARM_MESSAGE_ROBOT_SET_READY_H

#include <ros/service_traits.h>


#include <robotarm/Robot_Set_ReadyRequest.h>
#include <robotarm/Robot_Set_ReadyResponse.h>


namespace robotarm
{

struct Robot_Set_Ready
{

typedef Robot_Set_ReadyRequest Request;
typedef Robot_Set_ReadyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Robot_Set_Ready
} // namespace robotarm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotarm::Robot_Set_Ready > {
  static const char* value()
  {
    return "15c5ba1c738eafebff9be7bf85aaac80";
  }

  static const char* value(const ::robotarm::Robot_Set_Ready&) { return value(); }
};

template<>
struct DataType< ::robotarm::Robot_Set_Ready > {
  static const char* value()
  {
    return "robotarm/Robot_Set_Ready";
  }

  static const char* value(const ::robotarm::Robot_Set_Ready&) { return value(); }
};


// service_traits::MD5Sum< ::robotarm::Robot_Set_ReadyRequest> should match 
// service_traits::MD5Sum< ::robotarm::Robot_Set_Ready > 
template<>
struct MD5Sum< ::robotarm::Robot_Set_ReadyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotarm::Robot_Set_Ready >::value();
  }
  static const char* value(const ::robotarm::Robot_Set_ReadyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotarm::Robot_Set_ReadyRequest> should match 
// service_traits::DataType< ::robotarm::Robot_Set_Ready > 
template<>
struct DataType< ::robotarm::Robot_Set_ReadyRequest>
{
  static const char* value()
  {
    return DataType< ::robotarm::Robot_Set_Ready >::value();
  }
  static const char* value(const ::robotarm::Robot_Set_ReadyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotarm::Robot_Set_ReadyResponse> should match 
// service_traits::MD5Sum< ::robotarm::Robot_Set_Ready > 
template<>
struct MD5Sum< ::robotarm::Robot_Set_ReadyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotarm::Robot_Set_Ready >::value();
  }
  static const char* value(const ::robotarm::Robot_Set_ReadyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotarm::Robot_Set_ReadyResponse> should match 
// service_traits::DataType< ::robotarm::Robot_Set_Ready > 
template<>
struct DataType< ::robotarm::Robot_Set_ReadyResponse>
{
  static const char* value()
  {
    return DataType< ::robotarm::Robot_Set_Ready >::value();
  }
  static const char* value(const ::robotarm::Robot_Set_ReadyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTARM_MESSAGE_ROBOT_SET_READY_H
