// Generated by gencpp from file robotarm/Robot_StatusResponse.msg
// DO NOT EDIT!


#ifndef ROBOTARM_MESSAGE_ROBOT_STATUSRESPONSE_H
#define ROBOTARM_MESSAGE_ROBOT_STATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotarm
{
template <class ContainerAllocator>
struct Robot_StatusResponse_
{
  typedef Robot_StatusResponse_<ContainerAllocator> Type;

  Robot_StatusResponse_()
    : angle1(0)
    , angle2(0)
    , angle3(0)
    , angle4(0)
    , angle5(0)
    , angle6(0)  {
    }
  Robot_StatusResponse_(const ContainerAllocator& _alloc)
    : angle1(0)
    , angle2(0)
    , angle3(0)
    , angle4(0)
    , angle5(0)
    , angle6(0)  {
  (void)_alloc;
    }



   typedef int64_t _angle1_type;
  _angle1_type angle1;

   typedef int64_t _angle2_type;
  _angle2_type angle2;

   typedef int64_t _angle3_type;
  _angle3_type angle3;

   typedef int64_t _angle4_type;
  _angle4_type angle4;

   typedef int64_t _angle5_type;
  _angle5_type angle5;

   typedef int64_t _angle6_type;
  _angle6_type angle6;




  typedef boost::shared_ptr< ::robotarm::Robot_StatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotarm::Robot_StatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Robot_StatusResponse_

typedef ::robotarm::Robot_StatusResponse_<std::allocator<void> > Robot_StatusResponse;

typedef boost::shared_ptr< ::robotarm::Robot_StatusResponse > Robot_StatusResponsePtr;
typedef boost::shared_ptr< ::robotarm::Robot_StatusResponse const> Robot_StatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotarm::Robot_StatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotarm::Robot_StatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotarm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotarm::Robot_StatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotarm::Robot_StatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarm::Robot_StatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarm::Robot_StatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarm::Robot_StatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarm::Robot_StatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotarm::Robot_StatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c399c55e88916c8521493cd3f2b99104";
  }

  static const char* value(const ::robotarm::Robot_StatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc399c55e88916c85ULL;
  static const uint64_t static_value2 = 0x21493cd3f2b99104ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotarm::Robot_StatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotarm/Robot_StatusResponse";
  }

  static const char* value(const ::robotarm::Robot_StatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotarm::Robot_StatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 angle1\n\
int64 angle2\n\
int64 angle3\n\
int64 angle4\n\
int64 angle5\n\
int64 angle6\n\
\n\
";
  }

  static const char* value(const ::robotarm::Robot_StatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotarm::Robot_StatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle1);
      stream.next(m.angle2);
      stream.next(m.angle3);
      stream.next(m.angle4);
      stream.next(m.angle5);
      stream.next(m.angle6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Robot_StatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotarm::Robot_StatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotarm::Robot_StatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "angle1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.angle1);
    s << indent << "angle2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.angle2);
    s << indent << "angle3: ";
    Printer<int64_t>::stream(s, indent + "  ", v.angle3);
    s << indent << "angle4: ";
    Printer<int64_t>::stream(s, indent + "  ", v.angle4);
    s << indent << "angle5: ";
    Printer<int64_t>::stream(s, indent + "  ", v.angle5);
    s << indent << "angle6: ";
    Printer<int64_t>::stream(s, indent + "  ", v.angle6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTARM_MESSAGE_ROBOT_STATUSRESPONSE_H
